## Preprocessing

In [8]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
import pandas as pd
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [9]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.

#  YOUR CODE GOES HERE
application_df = application_df.drop(columns=['EIN'])
application_df

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...
34294,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [10]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
unique_values = application_df.nunique()
unique_values

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [11]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
#  YOUR CODE GOES HERE
application_type = application_df['APPLICATION_TYPE'].value_counts()
application_type

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [12]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_type[application_type < 500].index)
application_types_to_replace

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [13]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"

classification_count = application_df["CLASSIFICATION"].value_counts()
classification_count

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [14]:
# You may find it helpful to look at CLASSIFICATION value counts >1

classification_value = classification_count.loc[classification_count>1]
classification_value

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [15]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`

classifications_to_replace = list(classification_count[classification_count < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [17]:
name_df= application_df['NAME'].value_counts()
name_df

NAME
PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: count, Length: 19568, dtype: int64

In [18]:
# Choose a cutoff value and create a list of names to be replaced
names_to_replace = list(name_type[name_df < 100].index)

# Replace in dataframe
for name in names_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(
        name, "Other")

# Check to make sure binning was successful
application_df['NAME'].value_counts()

NAME
Other                                                                 25987
PARENT BOOSTER USA INC                                                 1260
TOPS CLUB INC                                                           765
UNITED STATES BOWLING CONGRESS INC                                      700
WASHINGTON STATE UNIVERSITY                                             492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                         408
PTA TEXAS CONGRESS                                                      368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC                           331
ALPHA PHI SIGMA                                                         313
TOASTMASTERS INTERNATIONAL                                              293
MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS                       287
LITTLE LEAGUE BASEBALL INC                                              277
INTERNATIONAL ASSOCIATION OF LIONS CLUBS                                266
MOMS CLUB                                                               210
INTERNATIONAL ASSOCIATION OF SHEET METAL AIR RAIL & TRANSPORTATION      206
AMERICAN ASSOCIATION OF UNIVERSITY WOMEN                                197
FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA                    166
KNIGHTS OF COLUMBUS                                                     158
HABITAT FOR HUMANITY INTERNATIONAL INC                                  154
TENNESSEE ORDER OF THE EASTERN STAR                                     151
VETERANS OF FOREIGN WARS OF THE UNITED STATES AUXILIARY                 144
PTA UTAH CONGRESS                                                       140
THE UNITED STATES PONY CLUBS INC                                        136
CIVITAN INTERNATIONAL                                                   131
SIGMA BETA DELTA INC                                                    127
HONOR SOCIETY OF PHI KAPPA PHI                                          107
MONTANA 4-H FOUNDATION INC                                              107
WASHINGTON STATE GRANGE                                                 106
UNIVERSITY OF WYOMING                                                   105
DEMOLAY INTERNATIONAL                                                   104
SERTOMA INC                                                             103
Name: count, dtype: int64

In [19]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
dummies_application_df = pd.get_dummies(application_df)
dummies_application_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_ALPHA PHI SIGMA,NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES INC,NAME_AMERICAN ASSOCIATION OF UNIVERSITY WOMEN,NAME_CIVITAN INTERNATIONAL,NAME_DEMOLAY INTERNATIONAL,NAME_FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA,NAME_HABITAT FOR HUMANITY INTERNATIONAL INC,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34295,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34296,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34297,1,5000,1,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34298,1,36500179,0,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False

In [20]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
y = dummies_application_df['IS_SUCCESSFUL'].values
X = dummies_application_df.drop(columns='IS_SUCCESSFUL').values


# Split the preprocessed data into a training and testing dataset

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [21]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [24]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
hidden_nodes_layer1 = 80
hidden_nodes_layer2 = 30
hidden_nodes_layer3 = 10
number_input_features = len(X_train_scaled[0])

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim = number_input_features, activation = "relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation = "sigmoid"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="sigmoid"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_10 (Dense)            (None, 80)                6000

 dense_11 (Dense)            (None, 30)                2430

 dense_12 (Dense)            (None, 10)                310

 dense_13 (Dense)            (None, 1)                 11

=================================================================
Total params: 8751 (34.18 KB)
Trainable params: 8751 (34.18 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [25]:
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [26]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.5338 - accuracy: 0.7373
Epoch 2/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5016 - accuracy: 0.7573
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4968 - accuracy: 0.7559
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4933 - accuracy: 0.7607
Epoch 5/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4916 - accuracy: 0.7604
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4909 - accuracy: 0.7596
Epoch 7/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4893 - accuracy: 0.7614
Epoch 8/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4886 - accuracy: 0.7597
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4873 - accuracy: 0.7607
Epoch 10/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4870 - accuracy: 0.7618
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4858 - accuracy: 0.7621
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4846 - accuracy: 0.7620
Epoch 13/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4846 - accuracy: 0.7611
Epoch 14/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4842 - accuracy: 0.7613
Epoch 15/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4836 - accuracy: 0.7625
Epoch 16/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4830 - accuracy: 0.7625
Epoch 17/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4822 - accuracy: 0.7631
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4817 - accuracy: 0.7648
Epoch 19/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4818 - accuracy: 0.7623
Epoch 20/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4811 - accuracy: 0.7642
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4810 - accuracy: 0.7627
Epoch 22/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4805 - accuracy: 0.7633
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4800 - accuracy: 0.7632
Epoch 24/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4797 - accuracy: 0.7643
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4791 - accuracy: 0.7640
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4788 - accuracy: 0.7641
Epoch 27/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4790 - accuracy: 0.7637
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4782 - accuracy: 0.7652
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4781 - accuracy: 0.7654
Epoch 30/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4776 - accuracy: 0.7629
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4773 - accuracy: 0.7657
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4775 - accuracy: 0.7656
Epoch 33/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4771 - accuracy: 0.7657
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4768 - accuracy: 0.7650
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4764 - accuracy: 0.7652
Epoch 36/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4767 - accuracy: 0.7648
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4761 - accuracy: 0.7645
Epoch 38/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4759 - accuracy: 0.7660
Epoch 39/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4756 - accuracy: 0.7657
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4755 - accuracy: 0.7672
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4752 - accuracy: 0.7664
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4751 - accuracy: 0.7661
Epoch 43/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4748 - accuracy: 0.7668
Epoch 44/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4745 - accuracy: 0.7663
Epoch 45/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4746 - accuracy: 0.7672
Epoch 46/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4744 - accuracy: 0.7671
Epoch 47/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4741 - accuracy: 0.7667
Epoch 48/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4742 - accuracy: 0.7665
Epoch 49/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4739 - accuracy: 0.7660
Epoch 50/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4737 - accuracy: 0.7662
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4733 - accuracy: 0.7663
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4734 - accuracy: 0.7672
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4735 - accuracy: 0.7658
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4732 - accuracy: 0.7668
Epoch 55/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4731 - accuracy: 0.7657
Epoch 56/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4728 - accuracy: 0.7656
Epoch 57/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4727 - accuracy: 0.7663
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4726 - accuracy: 0.7666
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4722 - accuracy: 0.7677
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4726 - accuracy: 0.7671
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4722 - accuracy: 0.7665
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4722 - accuracy: 0.7667
Epoch 63/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4721 - accuracy: 0.7678
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4720 - accuracy: 0.7669
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4719 - accuracy: 0.7664
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4717 - accuracy: 0.7675
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4716 - accuracy: 0.7682
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4714 - accuracy: 0.7689
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4718 - accuracy: 0.7673
Epoch 70/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4716 - accuracy: 0.7682
Epoch 71/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4713 - accuracy: 0.7670
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4712 - accuracy: 0.7687
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4712 - accuracy: 0.7670
Epoch 74/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4709 - accuracy: 0.7682
Epoch 75/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4714 - accuracy: 0.7680
Epoch 76/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4715 - accuracy: 0.7678
Epoch 77/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4709 - accuracy: 0.7681
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4706 - accuracy: 0.7693
Epoch 79/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4709 - accuracy: 0.7679
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4706 - accuracy: 0.7670
Epoch 81/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4707 - accuracy: 0.7665
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4705 - accuracy: 0.7687
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4705 - accuracy: 0.7676
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4701 - accuracy: 0.7678
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4705 - accuracy: 0.7685
Epoch 86/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4700 - accuracy: 0.7687
Epoch 87/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4702 - accuracy: 0.7671
Epoch 88/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4703 - accuracy: 0.7690
Epoch 89/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4699 - accuracy: 0.7671
Epoch 90/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4698 - accuracy: 0.7685
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4698 - accuracy: 0.7683
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4697 - accuracy: 0.7684
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4696 - accuracy: 0.7684
Epoch 94/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4696 - accuracy: 0.7685
Epoch 95/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4696 - accuracy: 0.7675
Epoch 96/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4698 - accuracy: 0.7682
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4694 - accuracy: 0.7673
Epoch 98/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4697 - accuracy: 0.7668
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4692 - accuracy: 0.7680
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4697 - accuracy: 0.7677

In [28]:
# Evaluate the model using the test data

model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5041 - accuracy: 0.7515 - 1s/epoch - 5ms/step
Loss: 0.50406813621521, Accuracy: 0.7514868974685669

In [29]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
# Save the model to an HDF5 file# Export our model to HDF5 file
nn.save('AlphabetSoupCharity_Optimization.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(